FROM scratch

# docker build -t ghcr.io/flux-framework/flux-k8s-nio-data:latest .
# This is the Dockerfile used to generate
# The original file was from:
# https://anl.app.box.com/s/pveyyzrc2wuvg5tmxjzzwxeo561vh3r0
# And we needed to programatically add it.

# Download file: NiO-fcc-supertwist111-supershift000-S8.h5
# And place it in NiO directory 

COPY NiO-fcc-supertwist111-supershift000-S8.h5 ./NiO-fcc-supertwist111-supershift000-S8.h5
